variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$https://github.com/jake1318/SuiMind'

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "App deployed successfully."
